name: Deployment

on:
  workflow_dispatch:
    inputs:
      auth_service:
        description: 'Deploy auth-service'
        required: true
        type: string
      stripe_service:
        description: 'Deploy stripe-service'
        required: true
        type: string

jobs:
  deploy-stg-auth-service:
    runs-on: ubuntu-latest
    environment: stg
    if: ${{ inputs.auth_service == 'true' }}
    concurrency:
      group: stg-auth-service
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy auth-service
        run: echo "Deploying to stg auth-service on ${{ github.ref_name }}"

  deploy-prd-auth-service:
    needs: deploy-stg-auth-service
    runs-on: ubuntu-latest
    environment: prd
    concurrency:
      group: prd-auth-service
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy auth-service
        run: echo "Deploying to prod auth-service on ${{ github.ref_name }}"

  deploy-stg-stripe-service:
    runs-on: ubuntu-latest
    environment: stg
    if: ${{ inputs.stripe_service == 'true' }}
    concurrency:
      group: stg-stripe-service
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy stripe-service
        run: echo "Deploying to stg stripe-service on ${{ github.ref_name }}"

  deploy-prd-stripe-service:
    needs: deploy-stg-stripe-service
    runs-on: ubuntu-latest
    environment: prd
    concurrency:
      group: prd-stripe-service
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy stripe-service
        run: echo "Deploying to prod stripe-service on ${{ github.ref_name }}"
